const user = 
[{"number":1,"productid":7383,"productname":"imperdiet","productcategory":"Clothing","productprize":1245},
{"number":2,"productid":3407,"productname":"eget","productcategory":"Furniture","productprize":3920},
{"number":3,"productid":9314,"productname":"duis at","productcategory":"Furniture","productprize":2065},
{"number":4,"productid":4444,"productname":"erat","productcategory":"Sports","productprize":3959},
{"number":5,"productid":7171,"productname":"non","productcategory":"Electronic","productprize":4467},
{"number":6,"productid":2513,"productname":"neque","productcategory":"Electronic","productprize":4877},
{"number":7,"productid":8325,"productname":"sapien","productcategory":"Books","productprize":3582},
{"number":8,"productid":5848,"productname":"magna","productcategory":"Electronic","productprize":4582},
{"number":9,"productid":9923,"productname":"duis","productcategory":"Sports","productprize":389},
{"number":10,"productid":1476,"productname":"vulputate vitae","productcategory":"Clothing","productprize":642},
{"number":11,"productid":9565,"productname":"est","productcategory":"Clothing","productprize":1658},
{"number":12,"productid":7785,"productname":"congue","productcategory":"Electronic","productprize":4092},
{"number":13,"productid":6812,"productname":"tempus","productcategory":"Electronic","productprize":2969},
{"number":14,"productid":8136,"productname":"sodales","productcategory":"Sports","productprize":1471},
{"number":15,"productid":3874,"productname":"ipsum","productcategory":"Clothing","productprize":1405},
{"number":16,"productid":7804,"productname":"aliquam lacus","productcategory":"Furniture","productprize":3067},
{"number":17,"productid":8748,"productname":"hac habitasse","productcategory":"Furniture","productprize":380},
{"number":18,"productid":6308,"productname":"orci luctus","productcategory":"Electronic","productprize":2183},
{"number":19,"productid":1391,"productname":"posuere cubilia","productcategory":"Books","productprize":3646},
{"number":20,"productid":5173,"productname":"turpis","productcategory":"Books","productprize":2791},
{"number":21,"productid":5154,"productname":"natoque penatibus","productcategory":"Furniture","productprize":4031},
{"number":22,"productid":4779,"productname":"imperdiet","productcategory":"Furniture","productprize":4222},
{"number":23,"productid":2232,"productname":"nunc","productcategory":"Furniture","productprize":1177},
{"number":24,"productid":2953,"productname":"vulputate","productcategory":"Electronic","productprize":4766},
{"number":25,"productid":3945,"productname":"magna vestibulum","productcategory":"Clothing","productprize":3529},
{"number":26,"productid":3901,"productname":"nulla","productcategory":"Clothing","productprize":1395},
{"number":27,"productid":2317,"productname":"in est","productcategory":"Clothing","productprize":2942},
{"number":28,"productid":2315,"productname":"dolor vel","productcategory":"Furniture","productprize":1187},
{"number":29,"productid":1826,"productname":"tincidunt in","productcategory":"Books","productprize":412},
{"number":30,"productid":7248,"productname":"ipsum","productcategory":"Furniture","productprize":768},
{"number":31,"productid":8893,"productname":"rhoncus dui","productcategory":"Furniture","productprize":4858},
{"number":32,"productid":8713,"productname":"lobortis est","productcategory":"Books","productprize":1407},
{"number":33,"productid":2586,"productname":"quam turpis","productcategory":"Sports","productprize":3872},
{"number":34,"productid":6685,"productname":"turpis","productcategory":"Books","productprize":2020},
{"number":35,"productid":5099,"productname":"dictumst","productcategory":"Electronic","productprize":2607},
{"number":36,"productid":2224,"productname":"congue elementum","productcategory":"Sports","productprize":2962},
{"number":37,"productid":8720,"productname":"aenean","productcategory":"Books","productprize":3064},
{"number":38,"productid":1950,"productname":"amet","productcategory":"Books","productprize":261},
{"number":39,"productid":4647,"productname":"congue eget","productcategory":"Electronic","productprize":1974},
{"number":40,"productid":9856,"productname":"odio justo","productcategory":"Furniture","productprize":3002},
{"number":41,"productid":9558,"productname":"lacinia eget","productcategory":"Clothing","productprize":3518},
{"number":42,"productid":4121,"productname":"ipsum","productcategory":"Furniture","productprize":2230},
{"number":43,"productid":4969,"productname":"sagittis sapien","productcategory":"Furniture","productprize":3972},
{"number":44,"productid":2859,"productname":"eros elementum","productcategory":"Electronic","productprize":3799},
{"number":45,"productid":6811,"productname":"bibendum","productcategory":"Clothing","productprize":2538},
{"number":46,"productid":8390,"productname":"ipsum primis","productcategory":"Books","productprize":3611},
{"number":47,"productid":9156,"productname":"dapibus","productcategory":"Electronic","productprize":4547},
{"number":48,"productid":1509,"productname":"nam","productcategory":"Sports","productprize":1342},
{"number":49,"productid":8102,"productname":"turpis eget","productcategory":"Electronic","productprize":721},
{"number":50,"productid":1149,"productname":"luctus ultricies","productcategory":"Clothing","productprize":3853},
{"number":51,"productid":7030,"productname":"placerat","productcategory":"Sports","productprize":1954},
{"number":52,"productid":1609,"productname":"vivamus","productcategory":"Electronic","productprize":4384},
{"number":53,"productid":8406,"productname":"ipsum primis","productcategory":"Sports","productprize":4448},
{"number":54,"productid":7551,"productname":"ut blandit","productcategory":"Books","productprize":765},
{"number":55,"productid":6927,"productname":"luctus","productcategory":"Sports","productprize":3847},
{"number":56,"productid":4765,"productname":"tincidunt in","productcategory":"Electronic","productprize":2315},
{"number":57,"productid":8922,"productname":"justo","productcategory":"Books","productprize":3778},
{"number":58,"productid":4230,"productname":"habitasse platea","productcategory":"Sports","productprize":3398},
{"number":59,"productid":6040,"productname":"vel augue","productcategory":"Clothing","productprize":4064},
{"number":60,"productid":6987,"productname":"quis tortor","productcategory":"Electronic","productprize":1928},
{"number":61,"productid":5596,"productname":"maecenas pulvinar","productcategory":"Books","productprize":616},
{"number":62,"productid":4441,"productname":"libero non","productcategory":"Books","productprize":1897},
{"number":63,"productid":4746,"productname":"est risus","productcategory":"Clothing","productprize":3798},
{"number":64,"productid":4417,"productname":"facilisi cras","productcategory":"Sports","productprize":1255},
{"number":65,"productid":9203,"productname":"donec semper","productcategory":"Sports","productprize":3365},
{"number":66,"productid":3508,"productname":"neque sapien","productcategory":"Furniture","productprize":2112},
{"number":67,"productid":8030,"productname":"tortor eu","productcategory":"Sports","productprize":1308},
{"number":68,"productid":3870,"productname":"metus","productcategory":"Sports","productprize":2687},
{"number":69,"productid":5689,"productname":"diam nam","productcategory":"Electronic","productprize":3308},
{"number":70,"productid":8870,"productname":"nam dui","productcategory":"Clothing","productprize":1068},
{"number":71,"productid":8734,"productname":"libero","productcategory":"Sports","productprize":4577},
{"number":72,"productid":6408,"productname":"metus","productcategory":"Furniture","productprize":4660},
{"number":73,"productid":6540,"productname":"augue","productcategory":"Electronic","productprize":3299},
{"number":74,"productid":6597,"productname":"quam","productcategory":"Books","productprize":3963},
{"number":75,"productid":5647,"productname":"nisl","productcategory":"Clothing","productprize":4735},
{"number":76,"productid":7129,"productname":"lectus in","productcategory":"Clothing","productprize":2051},
{"number":77,"productid":9885,"productname":"penatibus","productcategory":"Sports","productprize":4234},
{"number":78,"productid":7615,"productname":"aenean","productcategory":"Electronic","productprize":3998},
{"number":79,"productid":6406,"productname":"sapien a","productcategory":"Sports","productprize":4077},
{"number":80,"productid":4457,"productname":"vestibulum ac","productcategory":"Books","productprize":2698},
{"number":81,"productid":5431,"productname":"ipsum","productcategory":"Books","productprize":2617},
{"number":82,"productid":7417,"productname":"at","productcategory":"Books","productprize":1569},
{"number":83,"productid":9001,"productname":"ultrices","productcategory":"Books","productprize":4738},
{"number":84,"productid":5827,"productname":"leo odio","productcategory":"Sports","productprize":473},
{"number":85,"productid":1287,"productname":"eget tempus","productcategory":"Sports","productprize":3150},
{"number":86,"productid":5949,"productname":"curabitur","productcategory":"Sports","productprize":3553},
{"number":87,"productid":7056,"productname":"ac enim","productcategory":"Books","productprize":4928},
{"number":88,"productid":5035,"productname":"ligula suspendisse","productcategory":"Electronic","productprize":2986},
{"number":89,"productid":6755,"productname":"at diam","productcategory":"Electronic","productprize":1192},
{"number":90,"productid":1122,"productname":"cras","productcategory":"Clothing","productprize":2169},
{"number":91,"productid":6014,"productname":"dolor","productcategory":"Furniture","productprize":4019},
{"number":92,"productid":7263,"productname":"varius ut","productcategory":"Books","productprize":4895},
{"number":93,"productid":3206,"productname":"faucibus","productcategory":"Furniture","productprize":1295},
{"number":94,"productid":8691,"productname":"magna","productcategory":"Books","productprize":3398},
{"number":95,"productid":5969,"productname":"felis","productcategory":"Books","productprize":794},
{"number":96,"productid":7962,"productname":"blandit lacinia","productcategory":"Furniture","productprize":1445},
{"number":97,"productid":3025,"productname":"est","productcategory":"Sports","productprize":4095},
{"number":98,"productid":3593,"productname":"nam tristique","productcategory":"Furniture","productprize":160},
{"number":99,"productid":1232,"productname":"id sapien","productcategory":"Books","productprize":352},
{"number":100,"productid":4430,"productname":"libero quis","productcategory":"Furniture","productprize":2179}]
export const getUser = function(page, limit) {
   let array = [];
   for(let i = (page-1)*limit; i<(page*limit); i++) {
    array.push(user[i]);
   }
    return array;
}

export const getLength = function() {
    return user.length;
}